= Solution Patterns: Template Name
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

Red Hat OpenShift Service Mesh adds a transparent layer on existing distributed applications without requiring any changes to the application code. The mesh introduces an easy way to create a network of deployed services that provides discovery, load balancing, service-to-service authentication, failure recovery, metrics, and monitoring. A service mesh also provides more complex operational functionality, including A/B testing, canary releases, access control, and end-to-end authentication.

Microservice architectures split the work of enterprise applications into modular services, which can make scaling and maintenance easier. However, as an enterprise application built on a microservice architecture grows in size and complexity, it becomes difficult to understand and manage. Service Mesh can address those architecture problems by capturing or intercepting traffic between services and can modify, redirect, or create new requests to other services.


**Included with OpenShift Container Platform Subscription**

A key benefit of OpenShift Service Mesh is that it, along with most of its critical dependencies (e.g., Istio, Jaeger, Kiali, Prometheus), is included and fully supported with the OpenShift Container Platform subscription. This integration ensures:

- **Enterprise Support**: Comprehensive support from Red Hat for both OpenShift Service Mesh and its dependencies.
- **Seamless Upgrades**: Coordinated updates with the OpenShift platform, ensuring compatibility and reducing operational overhead.
- **Cost Efficiency**: Organizations can leverage advanced microservices management capabilities without incurring additional licensing or support costs.

By standardizing these capabilities at the platform level and bundling them into the OpenShift subscription, OpenShift Service Mesh enables teams to build, scale, and manage microservices architectures with minimal complexity and maximum support. This allows developers to return their focus to innovation and delivering business value.

This solution brief demonstrates how OpenShift Service Mesh 3 empowers platform teams to manage traffic flows with precision, including showcasing a canary deployment for safe, incremental rollouts. Additionally, it highlights how observability insights help detect and resolve issues quickly, ensuring reliability and resiliency across hybrid cloud environments.

++++
 <br>
++++
[IMPORTANT]
====
**OpenShift Service Mesh 3.0** and **Gateway API** in OpenShift are Technology Preview features only. 

Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. 

link:https://access.redhat.com/support/offerings/techpreview[More details about Technology Preview terms]

This Solution Pattern will update as supported releases become generally available (GA).
====

*Contributors:* link:https://github.com/bugbiteme[Leon Levy]

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====

[#use-cases]
== Use cases

Common use cases that can be address with this architecture are:

- **Traffic Management**: Control the flow of traffic and API calls between services, make calls more reliable, and make the network more robust in the face of adverse conditions.

- **Service Identity and Security**: Provide services in the mesh with a verifiable identity and provide the ability to protect service traffic as it flows over networks of varying degrees of trustworthiness.

- **Policy Enforcement**: Apply organizational policy to the interaction between services, ensure access policies are enforced and resources are fairly distributed among consumers. Policy changes are made by configuring the mesh, not by changing application code.

- **Telemetry**: Gain understanding of the dependencies between services and the nature and flow of traffic between them, providing the ability to quickly identify issues.

include::01-pattern.adoc[]
